apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cool
  name: cool
---
apiVersion: v1
kind: Service
metadata:
  name: cool2
  namespace: cool
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
